### ISSUE TITLE
recheck http://purl.org/dsw/

### ISSUE THREAD

**Issue by baskaufs** [dbpedia/archivo#12]
When I initially suggested this ontology, I accidentally entered https:// instead of http:// The resulting check failed at the equality step because the ontology about statement did not match.

I retried submitting the IRI http://purl.org/dsw/ but the ontology was immediately rejected without going through all of the checks (as opposed to showing all of the checks and giving a final panel with the reason for rejecting). I'm not sure why the IRI was rejected the second time without actually running any checks beyond the initial "Index check".

If you can try rechecking the IRI http://purl.org/dsw/, that would be greats.

**Comment by yum-yab** [comment]
Hi, thanks for using Archivo!
The ontology was already in Archivo since June 2020, see here: https://archivo.dbpedia.org/info?o=http%3A//purl.org/dsw/. A click on the index check would have given you the link to the page, but I know that the addition debugging is a bit confusing, there is already an issue for that: https://github.com/dbpedia/archivo/issues/10. I'll fix that soon!

**Comment by baskaufs** [comment]
Thanks for the info. My bad. I tried searching but perhaps I used https: for that as well. 

I appreciate your response!
