### ISSUE TITLE
allow alternatives of rdfs:label, rdfs:comment

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/archivo#2]
https://github.com/dbpedia/Archivo/blob/master/shacl-library/LODE.ttl checks for rdfs:label, rdfs:comment.
But some ontologies use alternatives:
- of rdfs:label : skos:prefLabel, dc:title, dct:title, schema:name
- of rdfs:comment: dc:description, dct:description, schema:description

Please allow these as alteranative props in the SHACL shapes

Example about https://databus.dbpedia.org/ontologies/vocab.getty.edu/ontology/:

- [shaclReport on lodeMetadata](http://akswnc7.informatik.uni-leipzig.de/dstreitmatter/archivo/vocab.getty.edu/ontology/2020.08.17-182902/ontology_type=shaclReport_validates=lodeMetadata.ttl)
- complains about label
```
  sh:focusNode <http://vocab.getty.edu/ontology#ulan1316_principal_was> ;
  sh:resultMessage "rdfs:label is missing or is no Literal"@en ;
```
- We got
```
    skos:prefLabel "ulan1316_principal_was";
    dc:title "principal was - person";
```
- complains about comment
```
  sh:focusNode <http://vocab.getty.edu/ontology#aat2216_require> ;
  sh:resultMessage "rdfs:comment is missing or is no Literal"@en ;
```
- We got
```
    dct:description """things - require - things [in order to exist or work].
Example: broderie anglaise requires eyelets; compact disc players require compact discs""" .
```
- [generatedDocu](http://akswnc7.informatik.uni-leipzig.de/dstreitmatter/archivo/vocab.getty.edu/ontology/2020.08.17-182902/ontology_type=generatedDocu.html) with LODE looks fine, because it interprets skos:prefLabel and dct:description

**Comment by yum-yab** [comment]
Hey, thanks for the Feedback and for using Archivo!

The base for this test is the [LODE documentation](https://essepuntato.it/lode/) and there they do not mention skos:prefLabel, dct:description (just dc:description) or any other alternative you mentioned.

As far as I can see [in the docu](http://akswnc7.informatik.uni-leipzig.de/dstreitmatter/archivo/vocab.getty.edu/ontology/2020.08.17-182902/ontology_type=generatedDocu.html#objectproperties) the label/comment alternatives are not displayed.

But since it gets properly displayed for the [Parrot documentation](http://vocab.getty.edu/ontology) you use maybe you can write a similar shacl test for the requirements of the parrot documentation as an alternative for the LODE Metadata test, create a pull request and I add it to Archivo.

Regards,
Denis

**Comment by VladimirAlexiev** [comment]
You are right, I see it now.

I patched LODE to handle those and schema.org props for https://rawcdn.githack.com/euBusinessGraph/eubg-data/master/ontology/doc.html

But I guess that patch never made it.

**Comment by kurzum** [comment]
@VladimirAlexiev we would close your issue. 
There are only two ways this will improve:
* LODE allows more props and we update the SHACL Test
* you contribute a SHACL test to the library testing whatever you think should be tested....
