### ISSUE TITLE
Add bioregistry as IRI candidate discovery source 

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/archivo#23]
see e.g. https://bioregistry.io/registry/ero 
offer json output including download links  and uri scheme as starting point for Archivo

**Comment by cthoyt** [comment]
Hi @JJ-Author, I am one of the maintainers of the Bioregistry. I am happy to answer any questions you have about it, discuss potential new features, content, exports, etc.

**Comment by JJ-Author** [comment]
Hey, @cthoyt thanks for your message. Indeed i found that you also provide RDF here https://bioregistry.io/download 
but this option is not shown here https://bioregistry.io/registry/ when clicking the download button. Is there a reason for that? (live export vs. snashot releases?)

**Comment by cthoyt** [comment]
Yes, it's the case that the RDF dump is generated on the nightly build and isn't part of the live website. You can expect that it's up-to-date though, since everything is automated!

Direct download link: ~https://raw.githubusercontent.com/biopragmatics/bioregistry/main/exports/rdf/schema.ttl~ https://github.com/biopragmatics/bioregistry/blob/main/exports/rdf/bioregistry.ttl

**Comment by RiddhiMenroy** [comment]
Is this thread still active?
I'm very new to github, could you please guide me on what's going on in here

**Comment by JJ-Author** [comment]
Hey @RiddhiMenroy, with the issues tagged as "enhancements" we keep record of our wishlist. We might tackle these once we have free resources or a student that is interested in doing it.
But feel free to comment what you are looking for.

**Comment by RiddhiMenroy** [comment]
How can i volunteer for them

**Comment by cthoyt** [comment]
hi @JJ-Author and @RiddhiMenroy, is there anything I can do from the Bioregistry side to help this out?

**Comment by RiddhiMenroy** [comment]
Nothing yet, thanks!

**Comment by yum-yab** [comment]
Bioregistry is now part of the discovery process. 

I used the registry available at https://bioregistry.io/api/registry?format=json, and the `download_rdf` and the `download_owl` fields since all archivo needs are the RDF files.
Unfortunately many ontologies do not have that field, is there a better way to access turtle/rdfxml files of the bioregistry ontologies @cthoyt?

**Comment by cthoyt** [comment]
Many of the resources in the Bioregistry neither have an RDF nor OWL artifact associated with them, so this isn't a surprise. If I had to guess, maybe <5% of the resources for which an RDF or OWL actually exists do not have it already annotated in the Bioregistry (i.e., low false negative rate)

FYI, some of them might have `download_obo` which you can convert to OWL using [`robot`](https://robot.obolibrary.org/).

**Comment by yum-yab** [comment]
Ok, but the parsing of obo files (and generally more supported formats) is an issue of its own. I'll close this one in favor of [this one](https://github.com/dbpedia/archivo/issues/36)
