### ISSUE TITLE
http 500 error for an ontology if new version was fetched but could not be deployed to databus

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/archivo#33]
we need a strategy to resolve that somehow. it can happen that the databus will not work for a day and this would give an http 500 error for the info page and maybe even more for all ontologies that had an update during the outage. i dont know how long this error will persist until the next new version is found, but maybe this will stay forever until resolved manually.
hope that this can be fixed with databus 2.1 migration 

http 500 happend when new databus replaced the old one for the following ontologies on jun 30th
https://archivo.dbpedia.org/info?o=https://w3id.org/sense
https://archivo.dbpedia.org/info?o=https://w3id.org/lbd/aec3po/ontology
![image](https://github.com/dbpedia/archivo/assets/2630603/a5e57a92-fb76-4ff8-b551-941abd00d48a)

![image](https://github.com/dbpedia/archivo/assets/2630603/a2203fab-4618-4d22-85c8-90753e8ca747)

**Comment by yum-yab** [comment]
The error ocurred when there is a database entry but no corresponding artifact/dataset on the Databus. 
Since this is usually impossible, it probably happened during the migration of the Databus to 2.0

Anyway, there is now a message that says to open an issue here since this should never happen normally (database entries get added AFTER the commit to the Databus)
